### ISSUE TITLE
Default Branch Name Changes

### ISSUE THREAD

**Issue by AOrps** [Inter-Camp/start-here-guides#4]
## Purpose 
* To bring to light potential conflicts with developers on *nix kernels (i.e. Linux Distros and Macs) from the [README.md](README.md) file in terms of default branch name
  * Let me know if I should fix it or leave it be.

## Description
* Github has _relatively_ recently changed it's default branch name from `master` to `main`
  * https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

**Comment by fenegroni** [comment]
Is it because this repo has its master branch called `main` and the other repo has its main branch called `master`?
Unfortunately changing a branch name can add to confusion. The least painful change would be from `main` to `master` in this repo.

**Comment by AOrps** [comment]
Not changing the actual branch name for the repository, but rather potentially making a change in the README.md under the branch name where the default is master?

**Comment by stacykutyepov** [comment]
Thank you for reminding me to do it! I've updated the default branch
